spring:
  application:
    name: api
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true